
project_id = "pesnfpdwcojfomspprmf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[functions]
[functions.process-document]
verify_jwt = true
[functions.rag-query]
verify_jwt = true
