// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

console.log("import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ", import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// const SUPABASE_URL = "https://pesnfpdwcojfomspprmf.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlc25mcGR3Y29qZm9tc3Bwcm1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNDMwNDcsImV4cCI6MjA1NjcxOTA0N30.gLrfIXIF-p0YxiXlRct16grCuSrryR8fEQhUMzTH0h8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);